# Generated by Django 6.0.6 on 2026-06-26 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text="Identificador único (ex: 'pagina_corretores')", max_length=50, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subtitulo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, help_text='Formato: (62) 99999-9999', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (DD) 9XXXX-XXXX', regex='^\\(\\d{2}\\) 9\\d{4}-\\d{4}$')])),
                ('creci', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O CRECI deve conter apenas números.', regex='^\\d+$')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_corretores/')),
                ('bio', models.TextField(blank=True, help_text='Uma breve biografia ou citação do corretor.')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(help_text='Um parágrafo curto sobre o conteúdo.')),
                ('imagem_card', models.ImageField(help_text='Imagem de capa que aparecerá no card do site.', upload_to='blog_cards/')),
                ('tipo_conteudo', models.CharField(choices=[('link', 'Link Externo (Artigo, PDF, Notícia)'), ('embed', 'Conteúdo Incorporado (Vídeo, Gamma, Facebook)')], default='link', max_length=10)),
                ('link_url', models.URLField(blank=True, help_text="Se 'Tipo' for Link Externo, cole a URL completa aqui.", max_length=500, null=True)),
                ('embed_code', models.TextField(blank=True, help_text="Se 'Tipo' for Conteúdo Incorporado, cole o código HTML (iframe, etc.) aqui.", null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post do Blog',
                'verbose_name_plural': 'Posts do Blog',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('query_string', models.TextField(blank=True, help_text='Parâmetros da busca salvos')),
                ('resumo_busca', models.CharField(blank=True, help_text='Resumo amigável. Ex: Lançamentos em Setor Bueno até R$ 2M', max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('finalidade', models.CharField(choices=[('lancamento', 'Lançamento'), ('revenda', 'Revenda')], default='revenda', help_text="Deduzido do Título (ex: 'lançamento') ou 'Revenda' como padrão", max_length=20)),
                ('categoria', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], default='residencial', help_text='Baseado no <UsageType> do XML (Residencial/Comercial)', max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text="Deixe em branco se for 'Sob Consulta'", max_digits=12, null=True)),
                ('taxa_condominio', models.DecimalField(blank=True, decimal_places=2, help_text='Baseado no <PropertyAdministrationFee> do XML', max_digits=10, null=True)),
                ('iptu', models.DecimalField(blank=True, decimal_places=2, help_text='Baseado no <Iptu> do XML', max_digits=10, null=True)),
                ('quartos', models.IntegerField(blank=True, null=True)),
                ('suites', models.IntegerField(blank=True, null=True)),
                ('banheiros', models.IntegerField(blank=True, null=True)),
                ('vagas', models.IntegerField(blank=True, null=True)),
                ('area_util', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('andar', models.IntegerField(blank=True, help_text='Baseado no <UnitFloor> do XML', null=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='fotos_imoveis/')),
                ('em_destaque', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bairro')),
                ('caracteristicas', models.ManyToManyField(blank=True, help_text='Baseado nas <Features> do XML', to='core.caracteristica')),
                ('corretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.corretor')),
                ('tipo_imovel', models.ForeignKey(blank=True, help_text='Baseado no <PropertySubType> ou <PropertyType> do XML', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoimovel')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_imoveis/galeria/')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_secundarias', to='core.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('favoritos', models.ManyToManyField(blank=True, related_name='favoritado_por', to='core.imovel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
