# Generated by Django 5.0 on 2025-11-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Caracteristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConteudoPagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(
                        help_text="Identificador único (ex: 'pagina_corretores')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("subtitulo", models.TextField(blank=True)),
                (
                    "corpo",
                    models.TextField(
                        blank=True,
                        help_text="Conteúdo principal da página. Pode usar tags HTML.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Corretor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("creci", models.CharField(max_length=20)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_corretores/"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Uma breve biografia ou citação do corretor.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("mensagem", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoImovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaginaSobre",
            fields=[],
            options={
                "verbose_name": 'Página "Sobre"',
                "verbose_name_plural": 'Página "Sobre"',
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.conteudopagina",),
        ),
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                (
                    "finalidade",
                    models.CharField(
                        choices=[("lancamento", "Lançamento"), ("revenda", "Revenda")],
                        default="revenda",
                        help_text="Deduzido do Título (ex: 'lançamento') ou 'Revenda' como padrão",
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("residencial", "Residencial"),
                            ("comercial", "Comercial"),
                        ],
                        default="residencial",
                        help_text="Baseado no <UsageType> do XML (Residencial/Comercial)",
                        max_length=20,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deixe em branco se for 'Sob Consulta'",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "taxa_condominio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Baseado no <PropertyAdministrationFee> do XML",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "iptu",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Baseado no <Iptu> do XML",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("quartos", models.IntegerField(blank=True, null=True)),
                ("suites", models.IntegerField(blank=True, null=True)),
                ("banheiros", models.IntegerField(blank=True, null=True)),
                ("vagas", models.IntegerField(blank=True, null=True)),
                (
                    "area_util",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "andar",
                    models.IntegerField(
                        blank=True, help_text="Baseado no <UnitFloor> do XML", null=True
                    ),
                ),
                ("endereco", models.CharField(blank=True, max_length=120)),
                (
                    "imagem_principal",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_imoveis/"
                    ),
                ),
                ("em_destaque", models.BooleanField(default=False)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "bairro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.bairro",
                    ),
                ),
                (
                    "caracteristicas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Baseado nas <Features> do XML",
                        to="core.caracteristica",
                    ),
                ),
                (
                    "corretor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.corretor",
                    ),
                ),
                (
                    "tipo_imovel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Baseado no <PropertySubType> ou <PropertyType> do XML",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.tipoimovel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemImovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="fotos_imoveis/galeria/")),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens_secundarias",
                        to="core.imovel",
                    ),
                ),
            ],
        ),
    ]
