# Generated by Django 5.2.7 on 2025-11-02 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='em_destaque',
            field=models.BooleanField(default=False, help_text='Marcar para aparecer nos destaques da página inicial.'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='imagem_principal',
            field=models.ImageField(blank=True, help_text='A foto principal (capa) do imóvel.', null=True, upload_to='imoveis/principal/'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo Lead'), ('em_atendimento', 'Em Atendimento'), ('convertido', 'Convertido'), ('descartado', 'Descartado')], default='novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bairro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.corretor'),
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/galeria/')),
                ('descricao', models.CharField(blank=True, help_text="Ex: 'Vista da sala de estar'", max_length=100)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagens', to='core.imovel')),
            ],
        ),
    ]
