# Generated by Django 5.2.7 on 2025-11-02 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imovel_em_destaque_imovel_imagem_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemimovel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='corretor',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil do corretor (proporção 3:4)', null=True, upload_to='fotos_corretores/'),
        ),
        migrations.AlterField(
            model_name='imagemimovel',
            name='imagem',
            field=models.ImageField(upload_to='galeria_imoveis/'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bairro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='em_destaque',
            field=models.BooleanField(default=False, help_text="Marcar para aparecer na secção 'Destaques' da página inicial."),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem_principal',
            field=models.ImageField(blank=True, help_text='Foto principal (capa) do imóvel.', null=True, upload_to='fotos_imoveis/'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('revenda', 'Revenda'), ('lancamento', 'Lançamento')], default='revenda', max_length=30),
        ),
    ]
