# Generated by Django 5.2.7 on 2025-11-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_imagemimovel_descricao_remove_lead_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text="Identificador único da página (ex: 'pagina_corretores')", max_length=50, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título da Página')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo ou Descrição')),
            ],
            options={
                'verbose_name': 'Conteúdo de Página',
                'verbose_name_plural': 'Conteúdos de Páginas',
            },
        ),
        migrations.AddField(
            model_name='corretor',
            name='bio',
            field=models.TextField(blank=True, help_text='Uma breve biografia ou citação do corretor. Aparecerá no card dele.', verbose_name='Biografia'),
        ),
    ]
