# Generated by Django 6.0.6 on 2026-06-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alertabusca_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='lead',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.corretor'),
        ),
        migrations.AddField(
            model_name='lead',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.imovel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('atendimento', 'Em Atendimento'), ('visita', 'Visita Agendada'), ('proposta', 'Proposta / Negociação'), ('fechado', 'Fechamento'), ('standby', 'Standby'), ('arquivado', 'Arquivado'), ('lixeira', 'Lixeira')], default='novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
