# Generated by Django 5.2.7 on 2025-11-03 18:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conteudopagina_corretor_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='conteudopagina',
            options={},
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='area',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='tipo',
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_util',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área útil/privativa. Baseado no <LivingArea> do XML', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='banheiros',
            field=models.IntegerField(blank=True, help_text='Baseado no <Bathrooms> do XML', null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 3, 18, 5, 25, 815448, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('lancamento', 'Lançamento'), ('revenda', 'Revenda')], default='revenda', help_text='Baseado no <PublicationType> do XML', max_length=20),
        ),
        migrations.AddField(
            model_name='imovel',
            name='suites',
            field=models.IntegerField(blank=True, help_text='Baseado no <Suites> do XML', null=True),
        ),
        migrations.AlterField(
            model_name='conteudopagina',
            name='chave',
            field=models.CharField(help_text="Identificador único (ex: 'pagina_corretores')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='conteudopagina',
            name='subtitulo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conteudopagina',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='bio',
            field=models.TextField(blank=True, help_text='Uma breve biografia ou citação do corretor.'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_corretores/'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imagemimovel',
            name='imagem',
            field=models.ImageField(upload_to='fotos_imoveis/galeria/'),
        ),
        migrations.AlterField(
            model_name='imagemimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_secundarias', to='core.imovel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bairro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='em_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_imoveis/'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vagas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Deixe em branco se for 'Sob Consulta'", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, help_text='Selecione os detalhes do imóvel/condomínio. Baseado nas <Features> do XML', to='core.caracteristica'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.ForeignKey(blank=True, help_text='Baseado no <PropertyType> do XML', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoimovel'),
        ),
    ]
