# Generated by Django 5.2.7 on 2025-11-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_caracteristica_tipoimovel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='categoria',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], default='residencial', help_text='Categoria principal (deduzida do Tipo de Imóvel)', max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('lancamento', 'Lançamento'), ('revenda', 'Revenda')], default='revenda', help_text='Baseado no <PublicationType> do XML (ou deduzido do Título)', max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.ForeignKey(blank=True, help_text='Baseado no <PropertyType> ou <PropertySubType> do XML', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoimovel'),
        ),
    ]
