# Generated by Django 5.2.7 on 2025-11-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_imovel_categoria_alter_imovel_finalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='andar',
            field=models.IntegerField(blank=True, help_text='Baseado no <UnitFloor> do XML', null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='iptu',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Baseado no <Iptu> do XML', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='taxa_condominio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Baseado no <PropertyAdministrationFee> do XML', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_util',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='banheiros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, help_text='Baseado nas <Features> do XML', to='core.caracteristica'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='categoria',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], default='residencial', help_text='Baseado no <UsageType> do XML (Residencial/Comercial)', max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('lancamento', 'Lançamento'), ('revenda', 'Revenda')], default='revenda', help_text="Deduzido do Título (ex: 'lançamento') ou 'Revenda' como padrão", max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='suites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.ForeignKey(blank=True, help_text='Baseado no <PropertySubType> ou <PropertyType> do XML', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoimovel'),
        ),
    ]
