# Generated by Django 6.0.6 on 2026-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='cargo',
            field=models.CharField(choices=[('Corretor', 'Corretor de Imóveis'), ('Gerente', 'Gerente de Vendas'), ('Diretor', 'Diretor'), ('Administrativo', 'Administrativo / Backoffice')], default='Corretor', help_text='Cargo/Hierarquia no CRM', max_length=50),
        ),
        migrations.AddField(
            model_name='corretor',
            name='exibir_email',
            field=models.BooleanField(default=True, help_text='Exibir o e-mail na página pública?'),
        ),
        migrations.AddField(
            model_name='corretor',
            name='exibir_no_site',
            field=models.BooleanField(default=True, help_text='Mostrar este membro na página pública de Equipe?'),
        ),
        migrations.AddField(
            model_name='corretor',
            name='exibir_whatsapp',
            field=models.BooleanField(default=True, help_text='Exibir o botão de WhatsApp na página pública?'),
        ),
    ]
