# Generated by Django 5.2.7 on 2025-11-05 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imovel_andar_imovel_iptu_imovel_taxa_condominio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='creci',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O CRECI deve conter apenas números.', regex='^\\d+$')]),
        ),
    ]
