# Generated by Django 5.0 on 2025-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_imovel_andar_imovel_iptu_imovel_taxa_condominio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conteudopagina",
            name="corpo",
            field=models.TextField(
                blank=True,
                help_text="Conteúdo principal da página. Pode usar tags HTML.",
            ),
        ),
    ]
