# Generated by Django 5.2.7 on 2025-11-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_cliente_imovel_favoritos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="foto_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
