# Generated by Django 5.0 on 2025-11-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_conteudopagina_corpo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaginaSobre",
            fields=[],
            options={
                "verbose_name": 'Página "Sobre"',
                "verbose_name_plural": 'Página "Sobre"',
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.conteudopagina",),
        ),
    ]
