# Generated by Django 6.0.6 on 2026-06-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_corretor_cargo_corretor_exibir_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='comissao_equipe',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Porcentagem de bônus sobre vendas da equipe (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='corretor',
            name='comissao_venda_direta',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Porcentagem de comissão em venda direta (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='corretor',
            name='gerente_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='core.corretor'),
        ),
        migrations.AddField(
            model_name='lead',
            name='comissao_diretor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comissão bônus do diretor', max_digits=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='comissao_gerada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comissão do corretor que atendeu', max_digits=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='comissao_gerente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comissão bônus do gerente', max_digits=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='comissao_imobiliaria',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Receita líquida da casa', max_digits=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='comissao_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comissão Total da Imobiliária (Ex: 5%)', max_digits=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor final fechado da negociação', max_digits=15),
        ),
    ]
