# Generated by Django 5.2.7 on 2025-11-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='core.imovel'),
        ),
    ]
