# Generated by Django 5.2.7 on 2025-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_favoritos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(help_text='Um parágrafo curto sobre o conteúdo.')),
                ('imagem_card', models.ImageField(help_text='Imagem de capa que aparecerá no card do site.', upload_to='blog_cards/')),
                ('tipo_conteudo', models.CharField(choices=[('link', 'Link Externo (Artigo, PDF, Notícia)'), ('embed', 'Conteúdo Incorporado (Vídeo, Gamma, Facebook)')], default='link', max_length=10)),
                ('link_url', models.URLField(blank=True, help_text="Se 'Tipo' for Link Externo, cole a URL completa aqui.", max_length=500, null=True)),
                ('embed_code', models.TextField(blank=True, help_text="Se 'Tipo' for Conteúdo Incorporado, cole o código HTML (iframe, etc.) aqui.", null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post do Blog',
                'verbose_name_plural': 'Posts do Blog',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
