# Generated by Django 6.0.6 on 2026-07-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_corretor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='arquivo',
            field=models.FileField(blank=True, help_text="Se 'Tipo' for Upload de Arquivo, selecione o arquivo aqui.", null=True, upload_to='blog_arquivos/'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='tipo_conteudo',
            field=models.CharField(choices=[('link', 'Link Externo (Artigo, PDF, Notícia)'), ('embed', 'Conteúdo Incorporado (Vídeo, Gamma, Facebook)'), ('arquivo', 'Upload de Arquivo (PDF, PPT, HTML, etc)')], default='link', max_length=10),
        ),
    ]
