# Generated by Django 5.2.7 on 2025-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_postblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidaturaCorretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('creci', models.CharField(blank=True, help_text='Opcional, caso já possua.', max_length=20, null=True)),
                ('mensagem', models.TextField(blank=True, help_text='Opcional. Fale um pouco sobre você.')),
                ('curriculo', models.FileField(help_text='Anexe seu currículo (PDF ou DOCX).', upload_to='curriculos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidatura de Corretor',
                'verbose_name_plural': 'Candidaturas de Corretores',
                'ordering': ['-data_envio'],
            },
        ),
    ]
