# Generated by Django 6.0.6 on 2026-06-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cor_primaria',
            field=models.CharField(default='#C6A87C', max_length=7),
        ),
        migrations.AddField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='endereco_faturamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='client',
            name='portfolio_aluguel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='portfolio_lancamento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='portfolio_revenda',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='texto_quem_somos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
