# Generated by Django 6.0.6 on 2026-06-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_client_cor_primaria_client_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='endereco_faturamento',
        ),
        migrations.AddField(
            model_name='client',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rua',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CNPJ', max_length=4),
        ),
        migrations.AddField(
            model_name='client',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
