# Generated by Django 6.0.6 on 2026-06-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_client_endereco_faturamento_client_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gb_extra',
            field=models.IntegerField(default=0, help_text='Espaço extra comprado via Add-on (em GB)'),
        ),
        migrations.AddField(
            model_name='client',
            name='plano_ativo',
            field=models.CharField(choices=[('boutique', 'Boutique'), ('corporate', 'Corporate')], default='corporate', help_text='Plano atual do cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='status_assinatura',
            field=models.CharField(default='active', help_text='Status no Stripe (active, past_due, canceled, etc)', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
