# Generated by Django 6.0.6 on 2026-06-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_client_gb_extra_client_plano_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='exibir_blog',
            field=models.BooleanField(default=True, help_text='Exibir seção de Blog/Notícias'),
        ),
        migrations.AddField(
            model_name='client',
            name='exibir_equipe',
            field=models.BooleanField(default=True, help_text='Exibir seção Nossa Equipe'),
        ),
        migrations.AddField(
            model_name='client',
            name='subtitulo_equipe',
            field=models.CharField(blank=True, default='Especialistas dedicados a encontrar o imóvel ideal para você.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='titulo_equipe',
            field=models.CharField(blank=True, default='Nossa Equipe', max_length=150, null=True),
        ),
    ]
