# Generated by Django 6.0.6 on 2026-06-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_client_exibir_blog_client_exibir_equipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sobre_citacao',
            field=models.TextField(blank=True, default='Tal como a flor de lótus, florescemos onde poucos imaginam: entregando beleza e valor em toda a jornada dos nossos clientes.', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sobre_missao',
            field=models.TextField(blank=True, default='Proporcionar experiências imobiliárias únicas, que transcendam a simples transação. Construímos relações sólidas baseadas em confiança, clareza e um atendimento de excelência que reflete a mesma qualidade e sofisticação dos imóveis que representamos.', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sobre_subtitulo',
            field=models.CharField(blank=True, default='Descubra o propósito que nos move e a curadoria que nos define.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sobre_titulo',
            field=models.CharField(blank=True, default='A Nossa História', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sobre_visao',
            field=models.TextField(blank=True, default='Ser a principal referência em curadoria e atendimento personalizado no mercado imobiliário de médio e alto padrão. Aspiramos ser a primeira e única escolha para clientes exigentes que procuram não apenas um endereço, mas um verdadeiro refúgio.', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='texto_quem_somos',
            field=models.TextField(blank=True, default='Inspirados pela flor de lótus, símbolo milenar de pureza, resiliência e renascimento, trazemos renovação e integridade a cada negociação imobiliária.', null=True),
        ),
    ]
