# Generated by Django 6.0.6 on 2026-06-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_client_sobre_citacao_client_sobre_missao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='home_hero_destaque',
            field=models.CharField(blank=True, default='Renascimento.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='home_hero_subtitulo',
            field=models.TextField(blank=True, default='Curadoria especializada para transformar a complexidade do mercado na simplicidade do extraordinário. Descubra propriedades que transcendem o comum.', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='home_hero_tag',
            field=models.CharField(blank=True, default='O Padrão de Viver', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='home_hero_titulo',
            field=models.CharField(blank=True, default='O Seu Espaço de', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='home_manifesto_destaque',
            field=models.CharField(blank=True, default='Apresentamos novos começos.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='home_manifesto_texto',
            field=models.TextField(blank=True, default='Nascemos com o propósito de elevar a experiência de encontrar o seu lar. Trabalhamos apenas com uma seleção criteriosa de propriedades que oferecem design imponente, conforto absoluto e exclusividade.', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='home_manifesto_titulo',
            field=models.CharField(blank=True, default='Não vendemos imóveis.', max_length=150, null=True),
        ),
    ]
