# Generated by Django 6.0.6 on 2026-06-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_client_home_hero_destaque_client_home_hero_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comissao_padrao',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Comissão padrão da Imobiliária (ex: 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='client',
            name='taxa_corretor',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Taxa padrão para Corretores (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='client',
            name='taxa_diretor',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text='Taxa padrão para Diretores (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='client',
            name='taxa_gerente',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Taxa padrão para Gerentes (%)', max_digits=5),
        ),
    ]
