# Generated by Django 6.0.6 on 2026-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_client_comissao_padrao_client_taxa_corretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='empresa_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='empresa_creci',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='empresa_email',
            field=models.EmailField(blank=True, help_text='E-mail público de contato', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='empresa_endereco',
            field=models.TextField(blank=True, help_text='Endereço físico para aparecer no site', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='empresa_facebook',
            field=models.URLField(blank=True, help_text='Link do Facebook', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='empresa_instagram',
            field=models.URLField(blank=True, help_text='Link do Instagram', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='empresa_telefone',
            field=models.CharField(blank=True, help_text='Telefone principal (ex: (11) 99999-9999)', max_length=50, null=True),
        ),
    ]
