# Generated by Django 6.0.6 on 2026-07-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_client_empresa_cnpj_client_empresa_creci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='empresa_cnpj',
        ),
        migrations.RemoveField(
            model_name='client',
            name='empresa_endereco',
        ),
        migrations.RemoveField(
            model_name='client',
            name='empresa_telefone',
        ),
    ]
