# Generated by Django 6.0.6 on 2026-07-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_client_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='home_hero_bg_custom',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_hero_bg/'),
        ),
        migrations.AddField(
            model_name='client',
            name='home_hero_bg_preset',
            field=models.CharField(default='preset_1', help_text="Preset escolhido (preset_1 a preset_4) ou 'custom'", max_length=20),
        ),
    ]
